### ISSUE TITLE
Adjust LCD backlight for night and day modes

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/Kunteng_LCD3_firmware#1]
On LCD3, we can enable day and night modes. On night mode, the motor controller should enable the ebike lights.

To implement: On LCD3 configuration menu, user can set a value from 0 up to 10 for the LCD backlight, for both modes. A value of 0 disables backlight.

**Comment by lightcore-x** [comment]
@casainho is this feature implemented in version 0.12 now and can be closed or is it still incomplete?

**Comment by casainho** [comment]
Implemented.
