### ISSUE TITLE
Adjust the number of minutes for auto turn off the system

### ISSUE THREAD

**Issue by casainho** [OpenSource-EBike-firmware/Kunteng_LCD3_firmware#2]
To implement: On LCD3 configuration menu, user can set a value from 0 up to 255 minutes for auto turn off the system (will turn off the LCD3 and motor controller). A value of 0 disables the auto turn off.

**Comment by lightcore-x** [comment]
@casainho is this feature implemented in version 0.12 now and can be closed or is it still incomplete?

**Comment by casainho** [comment]
Implemented.
